---

mobility-platform/openapi.yml:
  spec:
    # TODO: understand why the schema is considered invalid in redocly only
    - '#/components/responses/Device/content'
    - '#/components/responses/Healthz/content'
    - '#/components/responses/Readyz/content'
