---

# see https://meta.stoplight.io/docs/spectral/01baf06bdd05a-create-a-ruleset#extend-an-existing-ruleset
extends: "spectral:oas"

# see https://docs.stoplight.io/docs/spectral/e5b9616d6d50c-rulesets#formats
formats:
  - oas3_1
