---

data_sources:
  device:
    read:
      path: /v1/device
      method: GET

  device_battery:
    read:
      path: /v1/device/battery
      method: GET

  device_wifi_configuration:
    read:
      path: /v1/device/wifi
      method: GET

  device_health:
    read:
      path: /v1/healthz
      method: GET

  readiness_status:
    read:
      path: /v1/readyz
      method: GET

resources:
  thing:
    create:
      path: /thing
      method: POST
    read:
      path: /thing/{id}
      method: GET
    update:
      path: /thing
      method: PUT
    delete:
      path: /thing/{id}
      method: DELETE